#!/bin/bash

set -e

# 1. Configure build environment
export PROJ_ROOT=$(realpath ${PWD})
export OUTPUT_ROOT=${PROJ_ROOT}/output
export LOG_DIR=${OUTPUT_ROOT}/log
export TOPDIR=${PROJ_ROOT}
# export TEMPLATECONF=$PROJ_ROOT/src/meta-pb-p231nb/conf/templates/default
export TEMPLATECONF=$PROJ_ROOT/src/meta-rity/meta/conf/templates/default/

# export http_proxy="http://192.168.1.205:1082"
# export https_proxy="http://192.168.1.205:1082"

export FINAL_DISTRO="rity-demo-image"

# The variables below only take affect once after the build created
export FINAL_MACHINE="pb-p231nb-emmc"
export NUMS_TASK="8"
export NUMS_THREAD_PERTASK="10"
##################################################################

mkdir -p ${LOG_DIR}

# 2. enter the yocto environment
# Here pass an empty string or specific path to prevent it from consuming script arguments
source src/poky/oe-init-build-env ${PROJ_ROOT}/build > /dev/null
export BUILD_DIR=$(realpath ${PWD})


LOCAL_CONF="${BUILD_DIR}/conf/local.conf"

# Edit the config (Recommand to run the first time or you changes the MTK_CUSTOM_LOCAL_CONF)
do_local_conf ()
{
    # The MACHINE may be 1. enio-720-evk, 2.genio-720-evk-norboot-ufs
    tee >> "${LOCAL_CONF}" << EOF

# ---- Realbom Custom ----
DL_DIR = "${TOPDIR}/downloads"
SSTATE_DIR = "${TOPDIR}/sstate-cache"
MACHINE= "${FINAL_MACHINE}"
BB_NUMBER_THREADS = "${NUMS_TASK}"
PARALLEL_MAKE = "-j${NUMS_THREAD_PERTASK}"

EOF
}

# Build the config and extract before building
prepare_build () {
    # Append the Realbom Custom config to the LOCAL_CONF
    if ! grep -q "Realbom Custom" ${LOCAL_CONF}; then
        echo "This is the first time run, setting the custom config to ${LOCAL_CONF}"
        do_local_conf
    fi

    # Check the git2 dir exist on downloads dir or not
    if [ ! -e "${TOPDIR}/downloads/git2" ]; then
        echo "Extracting the downloaded git2 tarball under downloads dir, this may take a long time"
        if [ -e "${TOPDIR}/downloads/git2.tar.gz" ]; then
            tar xf "${TOPDIR}/downloads/git2.tar.gz" -C "${TOPDIR}/downloads"
        fi
    fi

}

# Build the package by checking WORK_DIR status, if has changes, then do the whole works that after the patch
build_package_force ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -p package-name"
        return 1
    fi

    local PKG="$1"
    # 把 virtual/kernel 变成 virtual_kernel 作为日志文件名
    local LOG_NAME="${PKG//\//_}"
    local PKG_WORKDIR
    PKG_WORKDIR=$(bitbake -e "${PKG}" 2>/dev/null | grep '^WORKDIR=' | head -1 | cut -d'=' -f2- | tr -d '"')

    if [ -d "${PKG_WORKDIR}" ]; then
        local UNCOMMITTED
        UNCOMMITTED=$(cd "${PKG_WORKDIR}" && git status --porcelain 2>/dev/null | wc -l)
        if [ "${UNCOMMITTED}" -gt 0 ]; then
            echo ">>> Detected ${UNCOMMITTED} uncommitted change(s) in ${PKG} source"
            echo ">>> Forcing recompile to pick up devshell modifications"
            bitbake -f -c do_configure "${PKG}" -vv | tee "${LOG_DIR}/${LOG_NAME}.log"
            bitbake -f -c do_compile "${PKG}" -vv | tee -a "${LOG_DIR}/${LOG_NAME}.log"
            bitbake -f -c do_install "${PKG}" -vv | tee -a "${LOG_DIR}/${LOG_NAME}.log"
            bitbake -f -c do_deploy "${PKG}" -vv | tee -a "${LOG_DIR}/${LOG_NAME}.log"
            bitbake "${PKG}" >> "${LOG_DIR}/${LOG_NAME}.log" 2>&1
        else
            bitbake "${PKG}" -vv | tee "${LOG_DIR}/${LOG_NAME}.log"
        fi
    else
        echo ">>> ${PKG} workdir not found, doing full build"
        bitbake "${PKG}" -vv | tee "${LOG_DIR}/${LOG_NAME}.log"
    fi
    # Then build with automatically to clear the tainted flag that generated by the forced build
    ln -sf ${BUILD_DIR}/tmp/deploy/* ${TOPDIR}/output/
}

# Enter the devshell for specific package
enter_devshell ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -d package-name"
        return 1
    fi
    echo "Entering devshell for $@"
    bitbake -c devshell $@
}

# build the bootloader only
build_bootloader ()
{
    prepare_build
    echo "building bootloader without cleaning"
    build_package_force virtual/bootloader
}

# build the u-boot with clean first
clean_build_uboot ()
{
    prepare_build
    echo "Cleaning uboot building"
    bitbake -c clean virtual/bootloader
    echo "Starting Building uboot"
    bitbake virtual/bootloader -vv | tee ${LOG_DIR}/bootloader.log
    echo "Log saved on ${LOG_DIR}/bootloader.log"
    ln -sf ${BUILD_DIR}/tmp/deploy/* ${TOPDIR}/output/
}

# build the kernel only
build_kernel ()
{
    prepare_build
    echo "Starting building kernel without cleaning"
    # Get kernel workdir
    build_package_force virtual/kernel
}

# build the kernel with clean
clean_build_kernel ()
{
    prepare_build
    echo "Cleaning kernel building"
    bitbake -c clean virtual/kernel
    echo "Starting building kernel"
    bitbake virtual/kernel -vv | tee ${LOG_DIR}/kernel.log
    echo "Log saved on ${LOG_DIR}/kernel.log"
    ln -sf ${BUILD_DIR}/tmp/deploy/* ${TOPDIR}/output/
}

# build the whole image
build_image ()
{
    prepare_build
    echo "Starting building image(all)"
    bitbake ${FINAL_DISTRO}
    ln -sf ${BUILD_DIR}/tmp/deploy/* ${TOPDIR}/output/
    ln -sf ${BUILD_DIR}/tmp/work ${TOPDIR}/output/
}

# Run the bitbake-layers
build_bitbake_layers_command ()
{
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -l <command>"
        return 1
    fi
    bitbake-layers $@
    exit 0
}

# Run the custom bitbake command
build_bitbake_command ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -b <command>"
        return 1
    fi
    bitbake $@
    exit 0
}

# Show the finale environment for a package
build_environments ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -e <package>"
        return 1
    fi
    bitbake -e $1 > ${TOPDIR}/${1}.bb
}

# Show the append's info for a package
build_appends ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -A <package>"
        return 1
    fi
    bitbake show-appends $@
}

# Show the finale environment for a package
build_dependency ()
{
    prepare_build
    if [ $# -eq 0 ]; then
        echo "Usage: build.sh -g <package>"
        return 1
    fi
    
    # # Check if dot command exists
    # if ! command -v dot &> /dev/null
    # then
    #     echo "Error: dot could not be found. Please install graphviz."
    #     return 1
    # fi
    
    bitbake -g $1
    PNG_FILENAME=${1}_task.png
    PN_FILENAME=${1}_builtlist
    # echo "Generating $PNG_FILENAME on $TOPDIR, this may take some time"
    # dot -Tpng $BUILDDIR/task-depends.dot -o $TOPDIR/$PNG_FILENAME
    echo "Dependency graph $TOPDIR/$PNG_FILENAME Generate success"
    cp $BUILDDIR/pn-buildlist $TOPDIR/$PN_FILENAME
    echo "Dependency build list of $1 generated on $TOPDIR/$PN_FILENAME"
}

# help info
usage() {
    echo "Usage:"
    echo "  $0 [options]"
    echo ""
    echo "Options:"
    echo "  -c    make REALBOM_CUSTOM_LOCAL_CONF effects agains"
    echo "  -d    enter devshell"
    echo "  -u    build u-boot without clean first"
    echo "  -U    build u-boot with clean first"
    echo "  -k    build kernel without clean first"
    echo "  -K    build kernel with clean first"
    echo "  -i    build image"
    echo "  -A    showing the appends info"
    echo "  -e    showing the package environment info"
    echo "  -b    run bitbake full named command"
    echo "  -l    run bitbake-layers full named command
    echo "  -g    generate packages dependency graph"
    echo "  -t    configure and compile package with force, generally used on test case"
    echo "  -h    help"
    echo ""
    echo "Examples:"
    echo "  $0 -i         # build all that the image needed"
    echo "  $0 -k         # build kernel without clean first"
    echo "  $0 -u         # build u-boot without clean first"
    echo "  $0 -U         # build u-boot with clean first"
    echo "  $0 -b -c devshell virtual/kernel  # the same as bitbake -c devshell virtual/kernel"
    echo "  $0 -l show-layers  # the same as bitbake-layers show-layers"
    exit 1
}


# ===== main build =====
if [ $# -eq 0 ]; then
    usage
fi

while getopts "cduUkKbheligtA" opt; do
    case "$opt" in
        c) do_local_conf ;;
        d) enter_devshell "${@:2:1}";;
        u) build_bootloader ;;
        U) clean_build_uboot ;;
        k) build_kernel ;;
        K) clean_build_kernel ;;
        i) build_image ;;
        A) build_appends "$2" ;;
        e) build_environments "$2" ;;
        b) build_bitbake_command "${@:2}" ;;
        l) build_bitbake_layers_command "${@:2}" ;;
        g) build_dependency "${@:2}" ;;
        t) build_package_force "${@:2:1}" ;;
        h|*) usage ;;
    esac
done
